name: Java Ci With Gradle

on:                         # 트리거
  push:
    branches: [ "master" ]  # master branch에 push할 때
  pull_request:
    branches: [ "master" ]  # master branch에 PR 올릴 때

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest              # 아래의 내용이 설치 및 실행 (스텝스 아래 하이픈(-)이 각 스텝)

    steps:
      - uses: actions/checkout@v3       # ubuntu 환경에 레포를 끌어옴

      - name: Set up JDK 17             # JDK 17을 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Add permission
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build -Pprofile=dev

      - name: 테스트 결과 등록 #추가된 부분
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 테스트 실패 Lines 등록 #추가된 부분
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}


